# Nombre de la imagen
PROJECT=wallet-serving

install:
	npm i

start:
	npx react-native start

start-android-release:
	 npx react-native run-android --mode=release --verbose

.PHONY: install start start-android-release
