AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Task Definition
  WalletECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Wallet
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: arn:aws:iam::877306037129:role/LabRole
      TaskRoleArn: arn:aws:iam::877306037129:role/LabRole
      ContainerDefinitions:
        - Name: wallet-app
          Image: 877306037129.dkr.ecr.us-east-1.amazonaws.com/wallet-serving:latest
          Essential: true
          Memory: 256
          Cpu: 128
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: CODE
              Value: superSecret
            - Name: POSTGRES_DB
              Value: daidb
            - Name: POSTGRES_USER
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: NODE_ENV
              Value: production
            - Name: POSTGRES_HOST
              Value: wallet-serving-db-dbinstance-jg79hftmmnfg.ci6gprfovemt.us-east-1.rds.amazonaws.com
            - Name: POSTGRES_PORT
              Value: 5432
            - Name: AWS_S3_BUCKET_NAME
              Value: wallet-desa-api-2
            - Name: AWS_DEFAULT_REGION
              Value: us-east-1
            - Name: AWS_REGION
              Value: us-east-1
            - Name: SNS_TOPIC_ARN
              Value: arn:aws:sns:us-east-1:137318283310:wallet_topic
            - Name: WALLET_QUEUE_URL
              Value: https://sqs.us-east-1.amazonaws.com/137318283310/wallet_service_queue
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: Logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: Wallet

  # ECS Service
  WalletECSService:
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
      - WalletALBBackupTargetGroup
      - WalletALBListener
      - WalletALBListenerTest
    Type: AWS::ECS::Service
    Properties:
      Cluster: InfraBase-ECSCluster-f3Ia4koRrIVC
      LaunchType: FARGATE
      PlatformVersion: "1.3.0"
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: wallet-app
          ContainerPort: 8080
          TargetGroupArn: !Ref WalletALBTargetGroup
      TaskDefinition: !Ref WalletECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-06d9b5a99df36e776
            - subnet-0f9b9d231c33ead7d
          SecurityGroups:
            - sg-05e56045a333f903b
      # DeploymentController:
      #   Type: CODE_DEPLOY

  # ALB
  WalletALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WalletALB
      Type: application
      Subnets:
        - subnet-06d9b5a99df36e776
        - subnet-0f9b9d231c33ead7d
      SecurityGroups:
        - sg-0a13b17cbaf11ba1e

  # ALB Target Group
  WalletALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - WalletALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-05399000cf9132dee

  # ALB Backup Target Group
  WalletALBBackupTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - WalletALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-05399000cf9132dee

  # Listener for Production Traffic
  WalletALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WalletALBTargetGroup
      LoadBalancerArn: !Ref WalletALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:877306037129:certificate/31dc8217-aa4b-4162-942d-3bcd4d6dd906

  # Listener for Test Traffic
  WalletALBListenerTest:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WalletALB
      - WalletALBBackupTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WalletALBBackupTargetGroup
      LoadBalancerArn: !Ref WalletALB
      Port: 80
      Protocol: HTTP
