Resources:
  # Task Definition
  WalletECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Wallet
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: arn:aws:iam::137318283310:role/LabRole
      TaskRoleArn: arn:aws:iam::137318283310:role/LabRole
      ContainerDefinitions:
        - Name: wallet-app
          Image: 137318283310.dkr.ecr.us-east-1.amazonaws.com/wallet-serving:latest
          Essential: true
          Memory: 256
          Cpu: 128
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: CODE
              Value: superSecret
            - Name: POSTGRES_DB
              Value: daidb
            - Name: POSTGRES_USER
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: POSTGRES_HOST
              Value: localhost
            - Name: POSTGRES_PORT
              Value: 5432
            - Name: AWS_S3_BUCKET_NAME
              Value: dis-desa-web-dev
            - Name: AWS_DEFAULT_REGION
              Value: us-east-1
            - Name: AWS_REGION
              Value: us-east-1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: Logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: Wallet

  # ECS Service
  WalletECSService:
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
      - WalletALBListener
    Type: AWS::ECS::Service
    Properties:
      Cluster: InfraBase-ECSCluster-3dDDnuOBUwp3
      LaunchType: FARGATE
      PlatformVersion: "1.3.0"
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: wallet-app
          ContainerPort: 8080
          TargetGroupArn: !Ref WalletALBTargetGroup
      TaskDefinition: !Ref WalletECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-084898bfe05cc94c8
            - subnet-0ebb59b6f23cde65b
          SecurityGroups:
            - sg-09fb4d8fdcb58602a
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false

  # ALB
  WalletALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WalletALB
      Type: application
      Subnets:
        - subnet-084898bfe05cc94c8
        - subnet-0ebb59b6f23cde65b
      SecurityGroups:
        - sg-08bcde548e566e797

  # ALB Target Group
  WalletALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - WalletALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-0a76e8c3474875e28

  # Listener
  WalletALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WalletALBTargetGroup
      LoadBalancerArn: !Ref WalletALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:137318283310:certificate/cf6356d6-bc02-485e-8f76-a15e9fd9a5b4

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: daidb
      AllocatedStorage: "20"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: "15.4"
      MasterUsername: postgres
      MasterUserPassword: base1234
      VPCSecurityGroups:
        - sg-081d9a27c10dd5fa4
      Subnets:
        - subnet-084898bfe05cc94c8
        - subnet-0ebb59b6f23cde65b
