Resources:
  # Task Definition
  WalletECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Wallet
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: arn:aws:iam::371815123890:role/InfraBase-ExecutionRole-37sMbNnfBodD
      TaskRoleArn: arn:aws:iam::371815123890:role/InfraBase-TaskRole-OlWl6JdyH1Q9
      ContainerDefinitions:
        - Name: wallet-db
          Image: postgres
          Essential: true
          Memory: 256
          Cpu: 128
          Environment:
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: POSTGRES_DB
              Value: daidb
          PortMappings:
            - ContainerPort: 5432
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: Logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: WalletDB
        - Name: wallet-app
          Image: 371815123890.dkr.ecr.us-east-1.amazonaws.com/wallet-serving:latest
          Essential: true
          Memory: 256
          Cpu: 128
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: CODE
              Value: superSecret
            - Name: POSTGRES_DB
              Value: daidb
            - Name: POSTGRES_USER
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: POSTGRES_HOST
              Value: localhost
            - Name: POSTGRES_PORT
              Value: 5432
            - Name: AWS_S3_BUCKET_NAME
              Value: dis-desa-web-dev
            - Name: AWS_ACCESS_KEY_ID
              Value:
            - Name: AWS_SECRET_ACCESS_KEY
              Value:
            - Name: AWS_DEFAULT_REGION
              Value: us-east-1
            - Name: AWS_REGION
              Value: us-east-1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: Logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: Wallet

  # ECS Service
  WalletECSService:
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
      - WalletALBListener
    Type: AWS::ECS::Service
    Properties:
      Cluster: InfraBase-ECSCluster-LGxtNiUvnwOO
      LaunchType: FARGATE
      PlatformVersion: "1.3.0"
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: wallet-app
          ContainerPort: 8080
          TargetGroupArn: !Ref WalletALBTargetGroup
      TaskDefinition: !Ref WalletECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-0e2b48d919c240b3f
            - subnet-0204ab161c2fd6926
          SecurityGroups:
            - sg-0c659425934fb655b
            - sg-03076ea8a1a229cee
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false

  # ALB
  WalletALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WalletALB
      Type: application
      Subnets:
        - subnet-0e2b48d919c240b3f
        - subnet-0204ab161c2fd6926
      SecurityGroups:
        - sg-0c659425934fb655b
        - sg-03076ea8a1a229cee

  # ALB Target Group
  WalletALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - WalletALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-0abd5e319f3b8bb9e

  # Listener
  WalletALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WalletALBTargetGroup
      LoadBalancerArn: !Ref WalletALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:371815123890:certificate/cbcf4f53-a658-4b95-b4e2-7c54ee84d289
