Resources:
  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: desa-api-2

  # Task Definition
  WalletECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Wallet
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: arn:aws:iam::137318283310:role/LabRole
      TaskRoleArn: arn:aws:iam::137318283310:role/LabRole
      ContainerDefinitions:
        - Name: wallet-app
          Image: 137318283310.dkr.ecr.us-east-1.amazonaws.com/wallet-serving:latest
          Essential: true
          Memory: 256
          Cpu: 128
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: CODE
              Value: superSecret
            - Name: POSTGRES_DB
              Value: daidb
            - Name: POSTGRES_USER
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: POSTGRES_HOST
              Value: wallet-serving-db-dbinstance-bsjoymycy4gi.ci6gprfovemt.us-east-1.rds.amazonaws.com
            - Name: POSTGRES_PORT
              Value: 5432
            - Name: AWS_S3_BUCKET_NAME
              Value: desa-api-2
            - Name: AWS_DEFAULT_REGION
              Value: us-east-1
            - Name: AWS_REGION
              Value: us-east-1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: Logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: Wallet

  # ECS Service
  WalletECSService:
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
      - WalletALBListener
    Type: AWS::ECS::Service
    Properties:
      Cluster: InfraBase-ECSCluster-uOPN78A1c2as
      LaunchType: FARGATE
      PlatformVersion: "1.3.0"
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: wallet-app
          ContainerPort: 8080
          TargetGroupArn: !Ref WalletALBTargetGroup
      TaskDefinition: !Ref WalletECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-022459452d75c7622
            - subnet-0b13d89cbf0c16de3
          SecurityGroups:
            - sg-03b1a58376beea64a
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false

  # ALB
  WalletALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WalletALB
      Type: application
      Subnets:
        - subnet-022459452d75c7622
        - subnet-0b13d89cbf0c16de3
      SecurityGroups:
        - sg-010dabc2738eb5e2c

  # ALB Target Group
  WalletALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - WalletALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-0769b29097342001b

  # Listener
  WalletALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WalletALB
      - WalletALBTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WalletALBTargetGroup
      LoadBalancerArn: !Ref WalletALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:137318283310:certificate/cf6356d6-bc02-485e-8f76-a15e9fd9a5b4
