AWSTemplateFormatVersion: "2010-09-09"
Description: Template para crear colas de SQS en AWS con acceso controlado y suscripciones a SNS

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: wallet_topic

  MySNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MySNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "SNS:Publish"
            Resource: !Ref MySNSTopic
          - Sid: "AllowEveryoneToSuscribe"
            Effect: Allow
            Principal:
              AWS: "*"
            Action: "SNS:Subscribe"
            Resource: "arn:aws:sns:us-east-1:877306037129:wallet_topic"

  WalletServiceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: wallet_service_queue
      VisibilityTimeout: 0

  WalletServiceQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref WalletServiceQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "SQS:SendMessage"
              - "SQS:ReceiveMessage"
              - "SQS:DeleteMessage"
              - "SQS:GetQueueUrl"
              - "SQS:GetQueueAttributes"
            Resource: !GetAtt WalletServiceQueue.Arn
          - Sid: "topic-subscription-arn:aws:sns:us-east-1:232171128702:CoreSNSTopic"
            Effect: Allow
            Principal:
              AWS: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt WalletServiceQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:sns:us-east-1:232171128702:CoreSNSTopic"
          - Sid: "topic-subscription-arn:aws:sns:us-east-1:696571260279:uade-inhouse"
            Effect: Allow
            Principal:
              AWS: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt WalletServiceQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:sns:us-east-1:696571260279:uade-inhouse"
          - Sid: "topic-subscription-arn:aws:sns:us-east-1:268120344536:criptosnstopic"
            Effect: Allow
            Principal:
              AWS: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt WalletServiceQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:sns:us-east-1:268120344536:criptosnstopic"

Outputs:
  WalletServiceQueueUrl:
    Description: URL de la cola Wallet Service
    Value: !Ref WalletServiceQueue
