AWSTemplateFormatVersion: "2010-09-09"
Description: Template para crear colas de SQS en AWS con acceso controlado y suscripciones a SNS

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: wallet_topic

  MySNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MySNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "SNS:Publish"
            Resource: !Ref MySNSTopic

  TestServiceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test_service_queue
      VisibilityTimeout: 0

  WalletServiceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: wallet_service_queue
      VisibilityTimeout: 0

  TestServiceQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref TestServiceQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "SQS:SendMessage"
            Resource: !GetAtt TestServiceQueue.Arn

  WalletServiceQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref WalletServiceQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "SQS:SendMessage"
              - "SQS:ReceiveMessage"
              - "SQS:DeleteMessage"
              - "SQS:GetQueueUrl"
              - "SQS:GetQueueAttributes"
            Resource: !GetAtt WalletServiceQueue.Arn

Outputs:
  WalletServiceQueueUrl:
    Description: URL de la cola Wallet Service
    Value: !Ref WalletServiceQueue

  TestServiceQueueUrl:
    Description: URL de la cola Test Service
    Value: !Ref TestServiceQueue
