const transactionsData = [
  {
    name: "Walmart",
    description: "Cafe Latte Grande",
    amount: 301.28,
    currency: "USD",
    status: "Pagada",
    date: "03/28/2024",
    userId: 1,
  },
  {
    name: "Starbucks",
    description: "Compra en linea",
    amount: 398.74,
    currency: "USD",
    status: "Pagada",
    date: "03/27/2024",
    userId: 1,
  },
  {
    name: "Amazon",
    description: "Cafe Latte Grande",
    amount: 385.55,
    currency: "USD",
    status: "Pagada",
    date: "03/26/2024",
    userId: 1,
  },
  {
    name: "Starbucks",
    description: "Articulos varios",
    amount: 225.96,
    currency: "USD",
    status: "Pagada",
    date: "03/25/2024",
    userId: 1,
  },
  {
    name: "Amazon",
    description: "Cafe Latte Grande",
    amount: 467.99,
    currency: "USD",
    status: "Pagada",
    date: "03/24/2024",
    userId: 1,
  },
  {
    name: "Amazon",
    description: "Suscripci\u00f3n mensual",
    amount: 28.29,
    currency: "USD",
    status: "Pagada",
    date: "03/23/2024",
    userId: 1,
  },
  {
    name: "Amazon",
    description: "Suscripci\u00f3n mensual",
    amount: 378.13,
    currency: "USD",
    status: "Pagada",
    date: "03/22/2024",
    userId: 1,
  },
  {
    name: "Apple Store",
    description: "Compra de electronicos",
    amount: 174.1,
    currency: "USD",
    status: "Pagada",
    date: "03/21/2024",
    userId: 1,
  },
  {
    name: "Starbucks",
    description: "Compra de electronicos",
    amount: 342.89,
    currency: "USD",
    status: "Pagada",
    date: "03/20/2024",
    userId: 1,
  },
  {
    name: "Walmart",
    description: "Suscripci\u00f3n mensual",
    amount: 463.04,
    currency: "USD",
    status: "Pagada",
    date: "03/19/2024",
    userId: 1,
  },
  {
    name: "Netflix",
    description: "Articulos varios",
    amount: 309.19,
    currency: "USD",
    status: "Pagada",
    date: "03/18/2024",
    userId: 1,
  },
  {
    name: "Amazon",
    description: "Compra de electronicos",
    amount: 367.01,
    currency: "USD",
    status: "Pagada",
    date: "03/17/2024",
    userId: 1,
  },
  {
    name: "Netflix",
    description: "Hamburguesa con queso",
    amount: 445.8,
    currency: "USD",
    status: "Pagada",
    date: "03/16/2024",
    userId: 1,
  },
  {
    name: "Walmart",
    description: "Articulos varios",
    amount: 305.3,
    currency: "USD",
    status: "Pagada",
    date: "03/15/2024",
    userId: 1,
  },
  {
    name: "Apple Store",
    description: "Cafe Latte Grande",
    amount: 431.67,
    currency: "USD",
    status: "Pagada",
    date: "03/14/2024",
    userId: 1,
  },
  {
    name: "Apple Store",
    description: "Articulos varios",
    amount: 321.33,
    currency: "USD",
    status: "Pagada",
    date: "03/13/2024",
    userId: 1,
  },
  {
    name: "Amazon",
    description: "Articulos varios",
    amount: 240.5,
    currency: "USD",
    status: "Pagada",
    date: "03/12/2024",
    userId: 1,
  },
  {
    name: "Apple Store",
    description: "Compra en linea",
    amount: 134.71,
    currency: "USD",
    status: "Pagada",
    date: "03/11/2024",
    userId: 1,
  },
  {
    name: "Netflix",
    description: "Compra de electronicos",
    amount: 430.91,
    currency: "USD",
    status: "Pagada",
    date: "03/10/2024",
    userId: 1,
  },
  {
    name: "Apple Store",
    description: "Cafe Latte Grande",
    amount: 305.62,
    currency: "USD",
    status: "Pagada",
    date: "03/09/2024",
    userId: 1,
  },
];

module.exports = { transactionsData };
